name: PHP-CS-Fixer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_mysql

      - name: Install PHP-CS-Fixer
        run: curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer
      - name: Make PHP-CS-Fixer executable
        run: chmod a+x php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: ./php-cs-fixer fix --verbose --diff --diff-format=udiff

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply PHP-CS-Fixer fixes"
