name: PHP Code Sniffer
on:
  push:
    branches:
      - main
jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, zip
    - name: Download PHP Code Sniffer
      run: wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - name: Make PHP Code Sniffer executable
      run: chmod +x phpcs.phar
    - name: Run PHP Code Sniffer
      run: ./phpcs.phar src --standard=PSR1,PSR12
